os:
  - osx

install:
  - brew install hugo
  - brew install https://raw.githubusercontent.com/hudochenkov/homebrew-sshpass/master/sshpass.rb

script:
  - hugo
  - rm public/images/cover.jpg public/images/cover-v1.2.0.jpg
  - sshpass -p ${SSH_PASS} ssh ${SSH_USER}@${SSH_HOST} "rm -rf /root/lizebang.top/blog/*"
  - sshpass -p ${SSH_PASS} scp -r public/* ${SSH_USER}@${SSH_HOST}:/root/lizebang.top/blog
